package com.tchat.wanxiaot.ui.theme

import androidx.compose.ui.graphics.Color

// Material You 风格的青绿色调色板
// 这些颜色在不支持动态颜色的设备上使用

// Light Theme Colors
val primaryLight = Color(0xFF006A67)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6FF7F2)
val onPrimaryContainerLight = Color(0xFF00201F)
val secondaryLight = Color(0xFF4A6362)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E6)
val onSecondaryContainerLight = Color(0xFF051F1E)
val tertiaryLight = Color(0xFF4B607C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD3E4FF)
val onTertiaryContainerLight = Color(0xFF041C35)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF4FBF9)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FBF9)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE5E3)
val onSurfaceVariantLight = Color(0xFF3F4948)
val outlineLight = Color(0xFF6F7978)
val outlineVariantLight = Color(0xFFBEC9C7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF5F3)
val surfaceContainerLight = Color(0xFFE8EFED)
val surfaceContainerHighLight = Color(0xFFE2E9E8)
val surfaceContainerHighestLight = Color(0xFFDDE4E2)

// Dark Theme Colors
val primaryDark = Color(0xFF4DDAD5)
val onPrimaryDark = Color(0xFF003735)
val primaryContainerDark = Color(0xFF00504D)
val onPrimaryContainerDark = Color(0xFF6FF7F2)
val secondaryDark = Color(0xFFB0CCCA)
val onSecondaryDark = Color(0xFF1C3533)
val secondaryContainerDark = Color(0xFF324B4A)
val onSecondaryContainerDark = Color(0xFFCCE8E6)
val tertiaryDark = Color(0xFFB3C8E8)
val onTertiaryDark = Color(0xFF1C314B)
val tertiaryContainerDark = Color(0xFF334863)
val onTertiaryContainerDark = Color(0xFFD3E4FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1514)
val onBackgroundDark = Color(0xFFDDE4E2)
val surfaceDark = Color(0xFF0E1514)
val onSurfaceDark = Color(0xFFDDE4E2)
val surfaceVariantDark = Color(0xFF3F4948)
val onSurfaceVariantDark = Color(0xFFBEC9C7)
val outlineDark = Color(0xFF899391)
val outlineVariantDark = Color(0xFF3F4948)
val surfaceContainerLowestDark = Color(0xFF090F0F)
val surfaceContainerLowDark = Color(0xFF161D1D)
val surfaceContainerDark = Color(0xFF1A2121)
val surfaceContainerHighDark = Color(0xFF252B2B)
val surfaceContainerHighestDark = Color(0xFF303636)
