package com.tchat.wanxiaot.ui.theme

import androidx.compose.ui.graphics.Color

// 更克制的品牌配色，强调统一、留白和稳定层次

// Light Theme Colors
val primaryLight = Color(0xFF205A56)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD4E8E3)
val onPrimaryContainerLight = Color(0xFF0F2C29)
val secondaryLight = Color(0xFF5D6663)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDCE4E1)
val onSecondaryContainerLight = Color(0xFF1B211F)
val tertiaryLight = Color(0xFF666B80)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE1E4EF)
val onTertiaryContainerLight = Color(0xFF212535)
val errorLight = Color(0xFFB3261E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF9DEDC)
val onErrorContainerLight = Color(0xFF410E0B)
val backgroundLight = Color(0xFFF6F3ED)
val onBackgroundLight = Color(0xFF181715)
val surfaceLight = Color(0xFFFBF8F2)
val onSurfaceLight = Color(0xFF181715)
val surfaceVariantLight = Color(0xFFE5E0D7)
val onSurfaceVariantLight = Color(0xFF5E5A53)
val outlineLight = Color(0xFF8C867D)
val outlineVariantLight = Color(0xFFD2CBC1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F1E9)
val surfaceContainerLight = Color(0xFFF0EBE4)
val surfaceContainerHighLight = Color(0xFFEAE5DD)
val surfaceContainerHighestLight = Color(0xFFE3DED6)

// Dark Theme Colors
val primaryDark = Color(0xFF9BC9C0)
val onPrimaryDark = Color(0xFF103633)
val primaryContainerDark = Color(0xFF224B47)
val onPrimaryContainerDark = Color(0xFFD4E8E3)
val secondaryDark = Color(0xFFC0C8C5)
val onSecondaryDark = Color(0xFF2A3230)
val secondaryContainerDark = Color(0xFF404846)
val onSecondaryContainerDark = Color(0xFFDCE4E1)
val tertiaryDark = Color(0xFFC2C7DC)
val onTertiaryDark = Color(0xFF2E3345)
val tertiaryContainerDark = Color(0xFF454A61)
val onTertiaryContainerDark = Color(0xFFE1E4EF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFF9DEDC)
val backgroundDark = Color(0xFF121311)
val onBackgroundDark = Color(0xFFE8E1D8)
val surfaceDark = Color(0xFF171816)
val onSurfaceDark = Color(0xFFE8E1D8)
val surfaceVariantDark = Color(0xFF48453F)
val onSurfaceVariantDark = Color(0xFFCAC4BB)
val outlineDark = Color(0xFF968F87)
val outlineVariantDark = Color(0xFF4C4943)
val surfaceContainerLowestDark = Color(0xFF0F100E)
val surfaceContainerLowDark = Color(0xFF1A1B18)
val surfaceContainerDark = Color(0xFF1E201D)
val surfaceContainerHighDark = Color(0xFF292B27)
val surfaceContainerHighestDark = Color(0xFF343632)
